# 写星号配置 是为了让其他工具可以读取该配置，实现匹配
# 一定要写成两个星号，否则会被 pnpm 识别为注释
#
# 出现故障 匹配范围过大 导致 .vercel 内的垃圾文件也被匹配到 被错误使用了。
packages:
  - "packages/*"
  - "demos/*"
  - "utils"
  - "learn-create-compoents-lib/*"
  # 配置系列的依赖包 为了实现便捷快速的配置分发
  - "configs-package/*"

catalog:
  typescript: 5.4.5
  lodash-es: 4.17.21
