name: monorepo-2
on:
  push:
    branches-ignore:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: amondnet/vercel-action@v25.1.1
        with:
          vercel-token: ${{ secrets.vercel_token }} # Required
          vercel-org-id: ${{ secrets.vercel_orgId}} #Required
          vercel-project-id: ${{ secrets.vercel_projectId}} #Required
          vercel-args: "--prod --cwd ./ --local-config ./packages/proj-2-vp2-custom-components/vercel.json"
          vercel-version: 34.1.2
          # working-directory: ./packages/proj-2-vp2-custom-components
          alias-domains: monorepo-2.ruancat6312.top
