# 参考资料
# https://github.com/marketplace/actions/vercel-action
# https://vercel.com/guides/how-can-i-use-github-actions-with-vercel

name: monorepo-2
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  push:
    branches-ignore:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      
      # https://aaronfrancis.com/2021/the-perfect-vercel-github-actions-deployment-pipeline
      - name: Setup Node 20
        uses: actions/setup-node@v2
        with:
          node-version: '20'
      
      - uses: actions/checkout@main
      - uses: amondnet/vercel-action@v25.1.1
        with:
          vercel-token: ${{ secrets.VERCL_TOKEN_MONOREPO_TEST }} # Required
          vercel-org-id: ${{ secrets.ORG_ID}} #Required
          vercel-project-id: ${{ secrets.PROJECT_ID}} #Required
          working-directory: ./packages/monorepo-2
          alias-domains: monorepo-2.ruancat6312.top
