# 参考资料
# https://vercel.com/guides/how-can-i-use-github-actions-with-vercel
# https://vercel.com/guides/how-to-alias-a-preview-deployment-using-the-cli

name: 自写的vercel部署工具
env:
  VERCEL_TOKEN: ${{ secrets.vercel_token }}
  VERCEL_ORG_ID: ${{ secrets.vercel_orgId }}
  VERCEL_PROJECT_ID: ${{ secrets.vercel_projectId }}

on:
  push:
    branches:
      # 避免高频率占用vercel资源，改成仅在main分支执行部署行为
      # - main
      # - dev-pause
      - dev

jobs:
  Deploy-Production:
    runs-on: ubuntu-latest
    steps:
      - name: 检出分支
        uses: actions/checkout@v4

      - name: 安装pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: |
            - args: [--global, vercel@latest, @dotenvx/dotenvx@latest, tsx@latest]

      - name: 安装node
        uses: actions/setup-node@v4
        with:
          node-version: 22.6.0
          cache: pnpm

      # - name: 开启 corepack
      #   run: corepack enable && corepack install

      - name: 检查pnpm版本
        run: pnpm -v

      - name: 检查node版本
        run: node -v

      - name: 安装整个项目的依赖
        run: pnpm i

      # - name: 用npm安装vercel cli工具
      #   run: npm i -g vercel@latest @dotenvx/dotenvx@latest vite-node@latest

      - name: 检查vercel cli版本
        run: vc -v

      - name: pnpm全局检查依赖包
        run: pnpm ls -g

      - name: 运行自写的vercel部署工具
        # https://dotenvx.com/docs/cis/github-actions#install-dotenvx
        run: |
          curl -sfS https://dotenvx.sh/install.sh | sh
          pnpm dotenvx run -- node --import=tsx ./demos/vercel-deploy-tool/src/index.ts
